version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: '5.6.x-apache'
#    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${DOCUMENT_VHOSTS-..}:/var/www/vhosts
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-../logs/apache2}:/var/log/apache2
      - ..:/workspace
  mysql:
    image: "mysql:5.7"
    container_name: '5.7.x-mysql'
#    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DIR-./config/mysql}:/etc/mysql/mysql.conf.d
      - ${MYSQL_DATA_DIR-../data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-../logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-time-zone='Asia/Seoul'
